name: Main

on: 
  push:
    tags:
    - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install VSCE
        run: sudo npm install -g vsce
      - name: Build LSP server & extension
        run: make all -j8
      - name: Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          files: release-assets/*
          prerelease: yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}